### ISSUE TITLE
Chart is broken in Firefox

### ISSUE THREAD

**Issue by pashagolub** [bytebase/star-history#117]
When displaying the chart in Firefox one more gray top layer is shown. Dots under this layer are inaccessible.

![image](https://user-images.githubusercontent.com/9463113/148800630-95ff2328-b295-4f66-987e-0592926205a2.png)

Kind regards!

**Comment by boojack** [comment]
@pashagolub Thanks for your nice hint, it might be fixed in #118. Please try again if you're free

**Comment by pashagolub** [comment]
Works like a charm! Thanks!
