### ISSUE TITLE
Add the project logo before the Star History title

### ISSUE THREAD

**Issue by tianzhou** [bytebase/star-history#168]
![CleanShot 2022-05-14 at 15 41 09@2x](https://user-images.githubusercontent.com/230323/168416180-f255f193-acd9-403d-90cc-087660e34a07.png)

If there is only a single repo on the chart, we can add the project logo before the title. We can fetch the project logo via the GitHub API.

Also, include in the downloaded image.

**Comment by Megrax** [comment]
@tianzhou I doubt if there really is a GitHub API to fetch a project's logo. Didn't find one in the [doc](https://docs.github.com/en/rest).  AFAIK, there is no such place for GitHub repositories to display logos. People usually include them in README or put in the website (if any).

There're a few options we may use as a logo for a project:
1. Logo in README.
2. Favicon icon of project's website.
3. The organization/owner's avatar.

All options above have limits, which way should we choose? How about let users manually provide a url of the logo?
