### ISSUE TITLE
Is there a way to make it less "xkcd feeling"?

### ISSUE THREAD

**Issue by CleanMachine1** [bytebase/star-history#182]
I am currently trying to implement it [here](https://github.com/tldr-pages/tldr/wiki/Project-history) however it doesn't fit the style very well, can the font be changed?

**Comment by boojack** [comment]
I've tried removing the "xkcd feeling", but it doesn't looks suitable. Since Star History has a special flavor to xkcd, so we still want to keep it ;) 
Too real maybe not good. Sorry for that I can't meet your needs.

**Comment by CleanMachine1** [comment]
Ok, well thanks for the reply

**Comment by oxygen-dioxide** [comment]
For anyone who is still asking for a more printed style of graph, I've found a good alternative: https://starchart.cc/
![image](https://github.com/star-history/star-history/assets/54425948/0a72ff2f-9132-436c-9727-b55fdac56d50)
