### ISSUE TITLE
Why does it not reflect the reduced number of stars?

### ISSUE THREAD

**Issue by rayrayraykk** [bytebase/star-history#185]
I appreciate that you can provide this valuable project, but I wonder why it can't reflect the reduced number of stars, thanks.

**Comment by boojack** [comment]
We can only get the star records from GitHub API but not unstar records. So it might be impossible to show the reducing star history :(

**Comment by SethFalco** [comment]
As far as I know, that's indeed the case.
The API only returns a current state of who starred the repository and when.

When someone unstars the repository, the record can no longer be obtained from the API.

The only way to generate a graph that can include when the star count goes down would be to poll the API and store the total count at set intervals. This wouldn't be able to complete historic data, but once that is implemented future data may be a more accurate representation.

For something like this, it could make sense to do that, but that'd be up to the maintainers. In general, I think I'd prefer to favor consistent results across the entire graph, and across other visualizations, so I think how things work now can be considered good.

**Comment by Heath123** [comment]
> That's indeed the case. The API only returns a current state of who starred the repository and when.
> 
> When someone unstars the repository, the record can no longer be obtained from the API.
> 
> The only way to generate a graph that can include when the star count goes down would be to snapshot the entire history, then to poll the API and store the total count at set intervals. This wouldn't be able to complete historic data, but once that is implemented future data may be a more accurate representation.
> 
> For something like this, it could make sense to do that, but that'd be up to the maintainers. In general, I think I'd prefer to favor consistency across the entire graph, and consistency with other visualizations (i.e. other sites/tools to generate graphs from the same data), so I think how things work now can be considered good.

I want to track a project that is getting unstarred quite quickly and see how fast it's going down, so in this case the data is not only helpful but also misleading (it looks like it's going up still)
