### ISSUE TITLE
Autocomplete for repository names

### ISSUE THREAD

**Issue by eungjun-yi** [bytebase/star-history#22]
It would be very helpful if it supports autocomplete for repository names.

**Comment by timqian** [comment]
Yes, but it seems not easy....... I will keep this issue open to see if we can do this later.
And there is an [extension version of star-history](https://github.com/timqian/star-history-plugin/) for a quick viw of star history of a project that you might find it useful

**Comment by tianzhou** [comment]
This is quite complex and out of our scope, we'd like to keep it simple.
