### ISSUE TITLE
feature: multiple projects in text input

### ISSUE THREAD

**Issue by peterdd** [bytebase/star-history#23]
maybe separated by space as simplest solution. And then split by space and loop?

**Comment by timqian** [comment]
Thanks for your suggestion. I might add this feature later. It will be great if you can help with a PR

**Comment by timqian** [comment]
After [adding many new features](https://github.com/timqian/star-history#updates) to this project. I think I am not going to add this feature, the input is not big enough to include many repos.

**Comment by peterdd** [comment]
Not big enough?

```css
#theForm {
 display: block;
}
#repo{
max-width:none;
width:80%;
}
```

Alternatively, you could make the url bookmarkable e.g. 
http://www.timqian.com/star-history/#torvalds/linux&timqian/star-history

shows graph for torvalds/linux and timqian/star-history

So someone could make a bookmark of the projects who he wants to monitor.

**Comment by timqian** [comment]
It is bookmarkable, just visit the link you provided

**Comment by peterdd** [comment]
I see. But only if I press F5 to reload , just editing/appending something in the address bar is not enough because the url part with the projects is an internal anchor # . 

How about http://www.timqian.com/star-history?torvalds/linux&timqian/star-history ?

**Comment by peterdd** [comment]
Or http://www.timqian.com/star-history?p[]=torvalds/linux&p[]=timqian/star-history to receive as array of projects?

**Comment by boojack** [comment]
Using `,` split the multi repos is supported right now. @peterdd
