### ISSUE TITLE
information: systematic stat weakness

### ISSUE THREAD

**Issue by peterdd** [bytebase/star-history#31]
The graph can show only the history of the current star givers.
It cannot show stars that where revoked later.

So lets face this situation:
1. someone creates a nice piece of software, many people like it and the project gets many stars.
2. suddenly something turns bad/evil with the projects (e.g it comes to public it contained virus or the last releases where rubbish and previous users move somewhere else) and now many people revoke their star from the project.

Now the star-history graph still would show an increasing interest, because the graph is calculated only from current star givers.

To resolve this it would be required to constantly monitor the stars (write to a database for instance weekly) of every project that you want to see in the graph, so you can detect when stars are taken away too.

**Comment by tianzhou** [comment]
Out of scope
