### ISSUE TITLE
filter duplicate projects

### ISSUE THREAD

**Issue by peterdd** [bytebase/star-history#32]
http://www.timqian.com/star-history/#torvalds/linux&torvalds/linux&torvalds/linux

should be filtered before adding them to the graph and legend.

**Comment by tianzhou** [comment]
The newlink, still happens https://star-history.com/#torvalds/linux&torvalds/linux&torvalds/linux

**Comment by boojack** [comment]
Fixed in https://github.com/bytebase/star-history/pull/99
