### ISSUE TITLE
Embed into website

### ISSUE THREAD

**Issue by sils** [bytebase/star-history#35]
Hey, could we embed the diagram of http://www.timqian.com/star-history/#coala-analyzer/coala into our website somehow easily?

CC @tushar-rishav and @mr-karan who are working on our website. CC @underyx who found this tool.

**Comment by mr-karan** [comment]
Sure, perhaps a better design though. I'll search for alternatives

**Comment by mr-karan** [comment]
Sure, I'll see around where we can integrate it

**Comment by timqian** [comment]
You can look into [getStarHistory.js](https://github.com/timqian/star-history/blob/gh-pages/src/getStarHistory.js). The function exported from this file returns the star history of certain repo  ` [{date: 2015-03-01,starNum: 12}, ...]`.

If you make use of that function. I hope you can make use of your own [token](https://github.com/timqian/star-history/blob/gh-pages/src/getStarHistory.js#L4)

**Comment by sils1297** [comment]
Yeah the token was a problem already in the past, I hoped we could get a cached image as a service somewhere and didn't need to do additional stuff on our server side. Well we might just drop it. We'll see.

**Comment by boojack** [comment]
@sils @mr-karan We have achieved this feature, check it out in the new [star-history.com](https://star-history.com/)
![image](https://user-images.githubusercontent.com/24653555/148505899-b616f62f-552d-40e2-aa26-8623d409efa9.png)
