### ISSUE TITLE
Firefox display bug

### ISSUE THREAD

**Issue by a455bcd9** [bytebase/star-history#39]
Hi,

Here is a screenshot of how the Star History looks like on my computer (Firefox 50 & Ubuntu 14.04): https://s17.postimg.org/pqbm03rkv/Capture_du_2016_12_10_20_48_25.png

I was on this page:
http://www.timqian.com/star-history/#facebook/react&vuejs/vue&angular/angular.js

Hope it can help.

Best,

Antoine.

**Comment by HowardHinnant** [comment]
I see the same behavior using Safari and different data sets.

**Comment by tianzhou** [comment]
It has gone several iteration. If the same issue happens, feel free to reopen and provide the new screenshot (the existing screenshot no longer works).
