### ISSUE TITLE
No caching

### ISSUE THREAD

**Issue by shaicoleman** [bytebase/star-history#42]
At the moment it always hits the API, it would be good to add caching caching, e.g. when sharing a link it doesn't use a lot of API calls

I suggest caching data via Redis with an expiry time of 1 hour

**Comment by pnowy** [comment]
@shaicoleman inspired by this project I've created similar one which has caching in firebase. You could take a look: https://github-stars-history.netlify.com/

**Comment by tianzhou** [comment]
We prefer to keep the stack simple and won't add caching unfortunately.
