### ISSUE TITLE
New chart design is hard to read

### ISSUE THREAD

**Issue by lpil** [bytebase/star-history#60]
The new chart is hard to read, especially when the lines are close together.

**Comment by or-else** [comment]
The  xkcd chart style is akin to Comic Sans font. OK in some circumstances but gets old fast.

**Comment by c-whitman** [comment]
Agreed. Would like to see it at least toggle-able. Also a raw-data download would be nice.

**Comment by timqian** [comment]
You can try https://old-star-history.t9t.io/ if you prefer the previous chart style

**Comment by mxmlnkn** [comment]
The font is one thing, but the lines just look like the rendering is broken. I thought my browser was bugged but the same result in chrome as in firefox:

![Screenshot from 2020-04-19 08-25-57](https://user-images.githubusercontent.com/6842824/79681116-8eced600-8217-11ea-8cd2-3e857ceb5396.png)

**Comment by waldyrious** [comment]
> You can try https://old-star-history.t9t.io if you prefer the previous chart style

@timqian That URL doesn't seem to be available anymore...

**Comment by lpil** [comment]
This other project doesn't have these problems so I've been using it instead.

https://seladb.github.io/StarTrack-js/

**Comment by timqian** [comment]
> > You can try https://old-star-history.t9t.io if you prefer the previous chart style
> 
> @timqian That URL doesn't seem to be available anymore...

Thanks for reporting, it is back now

**Comment by tianzhou** [comment]
It's been a while and we'd like to stick with the current design.

**Comment by oxygen-dioxide** [comment]
For anyone who is still asking for a more printed style of graph, I've found a good alternative: https://starchart.cc/
![image](https://github.com/star-history/star-history/assets/54425948/0a72ff2f-9132-436c-9727-b55fdac56d50)

**Comment by tianzhou** [comment]
I totally understand the readability concern. Several options are provided in the previous thread.

For star history, the doodle/sketch style is chosen intentionally. We don't plan to change it.
