### ISSUE TITLE
Chart tooltip no longer shows the values for all repos at a point 

### ISSUE THREAD

**Issue by lpil** [bytebase/star-history#61]
Previously a tooltip would show the values for all repos at a point in time that the mouse hovered over. The new version only shows a single language, making comparison impossible.

**Comment by timqian** [comment]
It is actually a bug for the old chart, the x axis for different repos are usually different

![](https://raw.githubusercontent.com/timqian/images/master/20190909103227.png)

> ps. I deployed another version of star history using the previous chart lib 
 https://old-star-history.t9t.io/
if you prefer the old chart style, you can try this one.
