### ISSUE TITLE
Repos can no longer be toggled between visible and invisible 

### ISSUE THREAD

**Issue by lpil** [bytebase/star-history#62]
I have a bookmarked chart that shows many repos. When viewing this it is useful to be able to toggle some repos so that the chart resizes to show the remaining ones more clearly, but this is not possible since the latest change.

**Comment by timqian** [comment]
I deployed another version of star history using the previous chart lib 
 https://old-star-history.t9t.io/
if you prefer the old chart style, you can try this one first

I will try to add this functionality to chart.xkcd too

**Comment by boojack** [comment]
👋 Hi @lpil, this feature has been released, check it on https://star-history.com when you are free.
