### ISSUE TITLE
Deprecation email about authentication using tokens

### ISSUE THREAD

**Issue by TheThirdOne** [bytebase/star-history#68]
Today I got an email containing the following (and information that shows it was sent because of a star-history and my token I have it linked with):
> Hi @TheThirdOne,
>
> Your personal access token was used as part of a query parameter to access an endpoint through the GitHub API
>
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team

It seems like this should be an easy fix; the affected lines seem to be: https://github.com/timqian/star-history/blob/7d1bbd8c950a70e97f598b981b13c1d6d5e92885/core/getStarHistory.js#L16-L23

**Comment by timqian** [comment]
@TheThirdOne  Thanks for pointing it out, this issue should have been fixed for the website, the extension will be updated soon

**Comment by TheThirdOne** [comment]
Thanks. It seems another email won't come again so it the fix must be working.

**Comment by timqian** [comment]
Reopening this issue as I met some problems publishing the new extension. Resubmitting the extension, not sure how long it will take, I will close this issue when the extension is published

**Comment by lpil** [comment]
Can you also update `https://old-star-history.t9t.io/` as it has features the new version does not yet have. Thanks

**Comment by tianzhou** [comment]
Version with the fix have been published
