### ISSUE TITLE
Comparing projects

### ISSUE THREAD

**Issue by Wikunia** [bytebase/star-history#74]
It would be nice to be able to compare projects in the sense how the number of stars have grown since it got launched. 
If there is a project from 2015 and one from 2018 one might be interested if one is growing faster which is hard to see atm. Therefore a possibility of changing the x axis to months since launch would be nice. + zoom functionality like #50 to focus on the first x months.

Thanks for the project.

**Comment by boojack** [comment]
Hi @Wikunia , we have upgrade this feature in https://github.com/bytebase/star-history/pull/110.
You can click the `Align timeline` button to compare projects by the same timeline.
![image](https://user-images.githubusercontent.com/24653555/148170108-012abdb1-2c90-4a3e-afbd-9907125bac93.png)
