### ISSUE TITLE
What about the history of GitHub followers?

### ISSUE THREAD

**Issue by ngzhio** [bytebase/star-history#79]
Maybe you can build a website to show the history of the growth of GitHub followers.

**Comment by antonkomarev** [comment]
@ngzhio you could try [Ÿ HŸPE](https://yhype.halp.im)! Right now it's in open alpha test. It can track new followings, unfollowings and profile views.

**Comment by tianzhou** [comment]
We will focus on github star. Follower is out of our scope.
