### ISSUE TITLE
star-history.t9t.io: Some unexpected error happened, try again

### ISSUE THREAD

**Issue by MarioKrenn6240** [bytebase/star-history#95]
Hi!
Thanks for the great tool and for providing the website [star-history.t9t.io](star-history.t9t.io). Last few days, when i run [https://star-history.t9t.io/#aspuru-guzik-group/selfies&aspuru-guzik-group/tequila&aspuru-guzik-group/chemical_vae](this request) or any other, it says `Some unexpected error happened, try again`.

Is there a way to fix this?

Thank you!
Mario

**Comment by tianzhou** [comment]
Maybe a hiccup. Seems to be fine now. Feel free to re-open and hopefully provide more context if it happens again.
